#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
#ifndef HP2APPLESDK_SWIFT_H
#define HP2APPLESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import Foundation;
@import ObjectiveC;
@import PassKit;
@import WatchConnectivity;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="HP2AppleSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
enum CardType : NSInteger;
@class UIImage;
@class NSDate;
enum CardStatusEnum : NSInteger;
SWIFT_CLASS_NAMED("Card")
@interface Card : NSObject
- (nonnull instancetype)initWithCardId:(NSString * _Nonnull)cardId cardType:(enum CardType)cardType serialNumber:(NSString * _Nonnull)serialNumber isRemote:(BOOL)isRemote deviceName:(NSString * _Nonnull)deviceName icon:(UIImage * _Nonnull)icon organizationName:(NSString * _Nonnull)organizationName relevantDate:(NSDate * _Nullable)relevantDate panId:(NSString * _Nullable)panId panLastFour:(NSString * _Nullable)panLastFour tokenId:(NSString * _Nullable)tokenId tokenLastFour:(NSString * _Nullable)tokenLastFour activationState:(enum CardStatusEnum)activationState OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)getCardId SWIFT_WARN_UNUSED_RESULT;
- (enum CardType)getCardType SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSerialNumber SWIFT_WARN_UNUSED_RESULT;
- (BOOL)getIsRemote SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDeviceName SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nonnull)getIcon SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getOrganizationName SWIFT_WARN_UNUSED_RESULT;
- (NSDate * _Nullable)getRelevantDate SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getPanId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getPanLastFour SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getTokenId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getTokenLastFour SWIFT_WARN_UNUSED_RESULT;
- (enum CardStatusEnum)getActivationState SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("CardDataModel")
@interface CardDataModel : NSObject
- (nonnull instancetype)initWithCardHolderName:(NSString * _Nonnull)cardHolderName cardID:(NSString * _Nonnull)cardID cardImageBase64:(NSString * _Nonnull)cardImageBase64 lastFourDigits:(NSString * _Nonnull)lastFourDigits localizedDescription:(NSString * _Nonnull)localizedDescription paymentNetwork:(NSString * _Nonnull)paymentNetwork OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCardHolderName:(NSString * _Nonnull)cardHolderName cardID:(NSString * _Nonnull)cardID cardImageBase64:(NSString * _Nonnull)cardImageBase64 lastFourDigits:(NSString * _Nonnull)lastFourDigits localizedDescription:(NSString * _Nonnull)localizedDescription paymentNetwork:(NSString * _Nonnull)paymentNetwork cardType:(NSString * _Nonnull)cardType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCardHolderName:(NSString * _Nonnull)cardHolderName cardID:(NSString * _Nonnull)cardID cardImageBase64:(NSString * _Nonnull)cardImageBase64 lastFourDigits:(NSString * _Nonnull)lastFourDigits localizedDescription:(NSString * _Nonnull)localizedDescription paymentNetwork:(NSString * _Nonnull)paymentNetwork encCard:(NSString * _Nonnull)encCard OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCardHolderName:(NSString * _Nonnull)cardHolderName cardID:(NSString * _Nonnull)cardID cardImageBase64:(NSString * _Nonnull)cardImageBase64 lastFourDigits:(NSString * _Nonnull)lastFourDigits localizedDescription:(NSString * _Nonnull)localizedDescription paymentNetwork:(NSString * _Nonnull)paymentNetwork cardType:(NSString * _Nonnull)cardType encCard:(NSString * _Nonnull)encCard OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)getCardHolderName SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getCardID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getCardImageBase64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getLastFourDigits SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getLocalizedDescription SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getPaymentNetwork SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getCardType SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getEncCard SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, CardDataModelType, open) {
  CardDataModelTypeCREDIT = 0,
  CardDataModelTypeDEBIT = 1,
};

@class NSEntityDescription;
@class NSManagedObjectContext;
SWIFT_CLASS_NAMED("CardExtensionData")
@interface CardExtensionData : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface CardExtensionData (SWIFT_EXTENSION(HP2AppleSDK))
@property (nonatomic, copy) NSString * _Nullable cardHolderName;
@property (nonatomic, copy) NSString * _Nullable cardID;
@property (nonatomic, copy) NSString * _Nullable cardImageBase64;
@property (nonatomic, copy) NSString * _Nullable lastFourDigits;
@property (nonatomic, copy) NSString * _Nullable localizedDescription;
@property (nonatomic, copy) NSString * _Nullable paymentNetwork;
@property (nonatomic, copy) NSString * _Nullable cardType;
@property (nonatomic, copy) NSString * _Nullable encCard;
@end

typedef SWIFT_ENUM(NSInteger, CardStatusEnum, open) {
  CardStatusEnumACTIVATED = 0,
  CardStatusEnumREQUIRES_ACTIVATION = 1,
  CardStatusEnumACTIVATING = 2,
  CardStatusEnumSUSPENDED = 3,
  CardStatusEnumDEACTIVATED = 4,
};

typedef SWIFT_ENUM(NSInteger, CardType, open) {
  CardTypeBARCODE = 0,
  CardTypePAYMENT_CARD = 1,
  CardTypeSECURE_ELEMENT = 2,
  CardTypeANY = 3,
};

SWIFT_CLASS_NAMED("CommEventResult")
@interface CommEventResult : NSObject
- (nonnull instancetype)initWithResult:(NSInteger)result detail:(NSInteger)detail message:(NSString * _Nonnull)message OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithResult:(NSInteger)result detail:(NSInteger)detail message:(NSString * _Nonnull)message resultObj:(id _Nullable)resultObj OBJC_DESIGNATED_INITIALIZER;
- (void)setResultWithResult:(NSInteger)result;
- (NSInteger)getResult SWIFT_WARN_UNUSED_RESULT;
- (void)setDetailWithDetail:(NSInteger)detail;
- (NSInteger)getDetail SWIFT_WARN_UNUSED_RESULT;
- (void)setMessageWithMessage:(NSString * _Nonnull)message;
- (NSString * _Nonnull)getMessage SWIFT_WARN_UNUSED_RESULT;
- (void)setResultObjectWithResultObj:(id _Nonnull)resultObj;
- (id _Nullable)getResultObject SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL_NAMED("CommProtocolInterface")
@protocol CommProtocolInterface
- (void)onPreExecute;
- (void)onPostExecuteWithResult:(CommEventResult * _Nonnull)result;
@end

SWIFT_CLASS_NAMED("CommEvents")
@interface CommEvents : NSObject <CommProtocolInterface>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)onPreExecute;
- (void)onPostExecuteWithResult:(CommEventResult * _Nonnull)result;
@end

typedef SWIFT_ENUM(NSInteger, DataBaseErrors, open) {
  DataBaseErrorsSUCCESS = 0,
  DataBaseErrorsFAILED_RETRIEVE_KEY_FROM_KEYCHAIN = 1,
  DataBaseErrorsIOS_VERSION_NOT_SUPPORTED = 2,
  DataBaseErrorsCONTEXT_MANAGER_NOT_FOUND = 3,
  DataBaseErrorsEMPTY_MANDATORY_FIELDS = 4,
  DataBaseErrorsINVALID_IMAGE = 5,
  DataBaseErrorsERROR_SAVING_DATABASE = 6,
};

@class UIViewController;
SWIFT_CLASS_NAMED("HP2")
@interface HP2 : NSObject
- (nonnull instancetype)initWithInstitutionCode:(NSString * _Nonnull)institutionCode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithInstitutionCode:(NSString * _Nonnull)institutionCode groupID:(NSString * _Nonnull)groupID OBJC_DESIGNATED_INITIALIZER;
- (NSInteger)updateDataBaseWithCardDataList:(NSArray<CardDataModel *> * _Nonnull)cardDataList SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isAvailable SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getVersion SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isAvailableForCardWithPanRefId:(NSString * _Nonnull)panRefId SWIFT_WARN_UNUSED_RESULT;
- (NSArray<Card *> * _Nullable)getCards SWIFT_WARN_UNUSED_RESULT;
- (CardDataModel * _Nullable)getCardDataModelWithCardID:(NSString * _Nonnull)cardID SWIFT_WARN_UNUSED_RESULT;
- (BOOL)executeProvisioningWithParentViewController:(UIViewController * _Nonnull)parentViewController cardholderName:(NSString * _Nonnull)cardholderName panLastFour:(NSString * _Nonnull)panLastFour cardDescr:(NSString * _Nonnull)cardDescr panId:(NSString * _Nonnull)panId pnp:(NSString * _Nonnull)pnp pushRecId:(NSString * _Nonnull)pushRecId events:(id <CommProtocolInterface> _Nullable)events error:(NSError * _Nullable * _Nullable)error;
- (BOOL)executeProvisioningWithParentViewController:(UIViewController * _Nonnull)parentViewController institutionCode:(NSString * _Nonnull)institutionCode cardholderName:(NSString * _Nonnull)cardholderName panLastFour:(NSString * _Nonnull)panLastFour cardDescr:(NSString * _Nonnull)cardDescr panId:(NSString * _Nonnull)panId pnp:(NSString * _Nonnull)pnp pushRecId:(NSString * _Nonnull)pushRecId events:(id <CommProtocolInterface> _Nullable)events error:(NSError * _Nullable * _Nullable)error;
- (BOOL)executeProvisioningOfEncryptedCardWithParentViewController:(UIViewController * _Nonnull)parentViewController cardholderName:(NSString * _Nonnull)cardholderName panLastFour:(NSString * _Nonnull)panLastFour cardDescr:(NSString * _Nonnull)cardDescr panId:(NSString * _Nonnull)panId pnp:(NSString * _Nonnull)pnp encCard:(NSString * _Nonnull)encCard events:(id <CommProtocolInterface> _Nullable)events error:(NSError * _Nullable * _Nullable)error;
- (BOOL)executeProvisioningOfEncryptedCardWithParentViewController:(UIViewController * _Nonnull)parentViewController institutionCode:(NSString * _Nonnull)institutionCode cardholderName:(NSString * _Nonnull)cardholderName panLastFour:(NSString * _Nonnull)panLastFour cardDescr:(NSString * _Nonnull)cardDescr panId:(NSString * _Nonnull)panId pnp:(NSString * _Nonnull)pnp encCard:(NSString * _Nonnull)encCard events:(id <CommProtocolInterface> _Nullable)events error:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PKAddPaymentPassViewController;
@class NSData;
@class PKAddPaymentPassRequest;
@class PKPaymentPass;
@interface HP2 (SWIFT_EXTENSION(HP2AppleSDK)) <PKAddPaymentPassViewControllerDelegate>
- (void)addPaymentPassViewController:(PKAddPaymentPassViewController * _Nonnull)controller generateRequestWithCertificateChain:(NSArray<NSData *> * _Nonnull)certificates nonce:(NSData * _Nonnull)nonce nonceSignature:(NSData * _Nonnull)nonceSignature completionHandler:(void (^ _Nonnull)(PKAddPaymentPassRequest * _Nonnull))handler;
- (void)addPaymentPassViewController:(PKAddPaymentPassViewController * _Nonnull)controller didFinishAddingPaymentPass:(PKPaymentPass * _Nullable)pass error:(NSError * _Nullable)error;
@end

@class WCSession;
@interface HP2 (SWIFT_EXTENSION(HP2AppleSDK)) <WCSessionDelegate>
- (void)session:(WCSession * _Nonnull)session activationDidCompleteWithState:(WCSessionActivationState)activationState error:(NSError * _Nullable)error SWIFT_AVAILABILITY(ios,introduced=9.3);
- (void)sessionDidBecomeInactive:(WCSession * _Nonnull)session;
- (void)sessionDidDeactivate:(WCSession * _Nonnull)session;
@end

@interface HP2 (SWIFT_EXTENSION(HP2AppleSDK))
- (NSArray<CardDataModel *> * _Nonnull)getCardsFromCoreData SWIFT_WARN_UNUSED_RESULT;
- (CardDataModel * _Nullable)getCardsFromCoreDataByCardIDWithCardID:(NSString * _Nonnull)cardID SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)convertImageToBase64StringWithImage:(UIImage * _Nonnull)image SWIFT_WARN_UNUSED_RESULT;
@end

@class PKIssuerProvisioningExtensionStatus;
@class PKIssuerProvisioningExtensionPassEntry;
SWIFT_AVAILABILITY(ios,introduced=14.0)
@interface HP2 (SWIFT_EXTENSION(HP2AppleSDK))
- (void)enablePanIdFilterWithEnable:(BOOL)enable;
- (PKIssuerProvisioningExtensionStatus * _Nonnull)getProvisioningExtensionStatus SWIFT_WARN_UNUSED_RESULT;
- (NSArray<PKIssuerProvisioningExtensionPassEntry *> * _Nonnull)getPassEntriesAvailable SWIFT_WARN_UNUSED_RESULT;
- (NSArray<PKIssuerProvisioningExtensionPassEntry *> * _Nonnull)getRemotePassEntriesAvailable SWIFT_WARN_UNUSED_RESULT;
- (void)getAddPaymentPassRequestWithCertificateChain:(NSArray<NSData *> * _Nonnull)certificates nonceSignature:(NSData * _Nonnull)nonceSignature nonce:(NSData * _Nonnull)nonce pushReceiptID:(NSString * _Nullable)pushReceiptID issuerEncCard:(NSString * _Nullable)issuerEncCard completionHandler:(void (^ _Nonnull)(PKAddPaymentPassRequest * _Nullable))completion;
@end

SWIFT_CLASS("_TtC11HP2AppleSDK9HP2Errors")
@interface HP2Errors : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("JwtAuthorization")
@interface JwtAuthorization : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
